class MyConsts():
    MIN_VALUE_VALIDATOR = 1
    MAX_VALUE_VALIDATOR = 32000


class FontConst():
    SIZE_FONT_REG = 14
    SIZE_FONT = 12
    SET_FONT_X_TITLE = 200
    SET_FONT_Y_TITLE = 800
    Y_POSITION = 750
    X_POSITION = 50
    Y_POSITION_UPDATE = 25
    NEW_PAGE_CHECK = 50
